services:
  - type: web
    name: starorbi-server-v4
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
    plan: free